package com.webbh.dmBanhang.mapper.dbo;

import com.webbh.dmBanhang.Model.cart;
import com.webbh.dmBanhang.Model.cartExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface cartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    long countByExample(cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    int deleteByExample(cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    int insert(cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    int insertSelective(cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    List<cart> selectByExample(cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    int updateByExampleSelective(@Param("row") cart row, @Param("example") cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    int updateByExample(@Param("row") cart row, @Param("example") cartExample example);
    int addtocart (@Param("id") int id);

}