package com.webbh.dmBanhang.mapper.dbo;

import com.webbh.dmBanhang.Model.giay;
import com.webbh.dmBanhang.Model.giayExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface giayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    long countByExample(giayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int deleteByExample(giayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int insert(giay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int insertSelective(giay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    List<giay> selectByExample(giayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    giay selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int updateByExampleSelective(@Param("row") giay row, @Param("example") giayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int updateByExample(@Param("row") giay row, @Param("example") giayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int updateByPrimaryKeySelective(giay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Giay
     *
     * @mbg.generated Mon Mar 04 23:34:41 ICT 2024
     */
    int updateByPrimaryKey(giay row);
}