package com.webbh.dmBanhang.mapper.dbo;

import com.webbh.dmBanhang.Model.ngaythang;
import com.webbh.dmBanhang.Model.ngaythangExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ngaythangMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	long countByExample(ngaythangExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	int deleteByExample(ngaythangExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	int insert(ngaythang row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	int insertSelective(ngaythang row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	List<ngaythang> selectByExample(ngaythangExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") ngaythang row, @Param("example") ngaythangExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.ngaythang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	int updateByExample(@Param("row") ngaythang row, @Param("example") ngaythangExample example);

	int save(@Param("thang") int thang , @Param("tuan") int tuan);
	
}