package com.webbh.dmBanhang.mapper.dbo;

import com.webbh.dmBanhang.Model.sdt;
import com.webbh.dmBanhang.Model.sdtExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface sdtMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	long countByExample(sdtExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	int deleteByExample(sdtExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	int insert(sdt row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	int insertSelective(sdt row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	List<sdt> selectByExample(sdtExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") sdt row, @Param("example") sdtExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	int updateByExample(@Param("row") sdt row, @Param("example") sdtExample example);

	List<sdt> getSDT();
}