package com.shop.demoShop.model;

import org.springframework.validation.annotation.Validated;

import jakarta.validation.constraints.NotBlank;

@Validated
public class accout {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.accout.aid
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.accout.username
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     * 
     */
    @NotBlank(message = "k de trong")
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.accout.email
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    @NotBlank(message = "k de trong")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.accout.passwork
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    @NotBlank(message = "k de trong")
    private String passwork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.accout.issell
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    private Integer issell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.accout.isadmin
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    private Integer isadmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.accout.aid
     *
     * @return the value of dbo.accout.aid
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.accout.aid
     *
     * @param aid the value for dbo.accout.aid
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.accout.username
     *
     * @return the value of dbo.accout.username
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.accout.username
     *
     * @param username the value for dbo.accout.username
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.accout.email
     *
     * @return the value of dbo.accout.email
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.accout.email
     *
     * @param email the value for dbo.accout.email
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.accout.passwork
     *
     * @return the value of dbo.accout.passwork
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public String getPasswork() {
        return passwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.accout.passwork
     *
     * @param passwork the value for dbo.accout.passwork
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public void setPasswork(String passwork) {
        this.passwork = passwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.accout.issell
     *
     * @return the value of dbo.accout.issell
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public Integer getIssell() {
        return issell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.accout.issell
     *
     * @param issell the value for dbo.accout.issell
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public void setIssell(Integer issell) {
        this.issell = issell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.accout.isadmin
     *
     * @return the value of dbo.accout.isadmin
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.accout.isadmin
     *
     * @param isadmin the value for dbo.accout.isadmin
     *
     * @mbg.generated Wed Feb 07 23:58:00 ICT 2024
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }
}