package com.shop.demoShop.model;

public class cartitem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.cartitem.idc
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	private Integer idc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.cartitem.hinhanhc
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	private String hinhanhc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.cartitem.idnguoidung
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	private Integer idnguoidung;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.cartitem.idsanpham
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	private Integer idsanpham;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.cartitem.soluong
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	private Integer soluong;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.cartitem.idc
	 * @return  the value of dbo.cartitem.idc
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public Integer getIdc() {
		return idc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.cartitem.idc
	 * @param idc  the value for dbo.cartitem.idc
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.cartitem.hinhanhc
	 * @return  the value of dbo.cartitem.hinhanhc
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public String getHinhanhc() {
		return hinhanhc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.cartitem.hinhanhc
	 * @param hinhanhc  the value for dbo.cartitem.hinhanhc
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setHinhanhc(String hinhanhc) {
		this.hinhanhc = hinhanhc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.cartitem.idnguoidung
	 * @return  the value of dbo.cartitem.idnguoidung
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public Integer getIdnguoidung() {
		return idnguoidung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.cartitem.idnguoidung
	 * @param idnguoidung  the value for dbo.cartitem.idnguoidung
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setIdnguoidung(Integer idnguoidung) {
		this.idnguoidung = idnguoidung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.cartitem.idsanpham
	 * @return  the value of dbo.cartitem.idsanpham
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public Integer getIdsanpham() {
		return idsanpham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.cartitem.idsanpham
	 * @param idsanpham  the value for dbo.cartitem.idsanpham
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setIdsanpham(Integer idsanpham) {
		this.idsanpham = idsanpham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.cartitem.soluong
	 * @return  the value of dbo.cartitem.soluong
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public Integer getSoluong() {
		return soluong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.cartitem.soluong
	 * @param soluong  the value for dbo.cartitem.soluong
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}
}