package com.shop.demoShop.model;

import java.util.ArrayList;
import java.util.List;

public class cartitemExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public cartitemExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdcIsNull() {
			addCriterion("idc is null");
			return (Criteria) this;
		}

		public Criteria andIdcIsNotNull() {
			addCriterion("idc is not null");
			return (Criteria) this;
		}

		public Criteria andIdcEqualTo(Integer value) {
			addCriterion("idc =", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotEqualTo(Integer value) {
			addCriterion("idc <>", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcGreaterThan(Integer value) {
			addCriterion("idc >", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcGreaterThanOrEqualTo(Integer value) {
			addCriterion("idc >=", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcLessThan(Integer value) {
			addCriterion("idc <", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcLessThanOrEqualTo(Integer value) {
			addCriterion("idc <=", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcIn(List<Integer> values) {
			addCriterion("idc in", values, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotIn(List<Integer> values) {
			addCriterion("idc not in", values, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcBetween(Integer value1, Integer value2) {
			addCriterion("idc between", value1, value2, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotBetween(Integer value1, Integer value2) {
			addCriterion("idc not between", value1, value2, "idc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcIsNull() {
			addCriterion("hinhanhc is null");
			return (Criteria) this;
		}

		public Criteria andHinhanhcIsNotNull() {
			addCriterion("hinhanhc is not null");
			return (Criteria) this;
		}

		public Criteria andHinhanhcEqualTo(String value) {
			addCriterion("hinhanhc =", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcNotEqualTo(String value) {
			addCriterion("hinhanhc <>", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcGreaterThan(String value) {
			addCriterion("hinhanhc >", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcGreaterThanOrEqualTo(String value) {
			addCriterion("hinhanhc >=", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcLessThan(String value) {
			addCriterion("hinhanhc <", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcLessThanOrEqualTo(String value) {
			addCriterion("hinhanhc <=", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcLike(String value) {
			addCriterion("hinhanhc like", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcNotLike(String value) {
			addCriterion("hinhanhc not like", value, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcIn(List<String> values) {
			addCriterion("hinhanhc in", values, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcNotIn(List<String> values) {
			addCriterion("hinhanhc not in", values, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcBetween(String value1, String value2) {
			addCriterion("hinhanhc between", value1, value2, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andHinhanhcNotBetween(String value1, String value2) {
			addCriterion("hinhanhc not between", value1, value2, "hinhanhc");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungIsNull() {
			addCriterion("idnguoidung is null");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungIsNotNull() {
			addCriterion("idnguoidung is not null");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungEqualTo(Integer value) {
			addCriterion("idnguoidung =", value, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungNotEqualTo(Integer value) {
			addCriterion("idnguoidung <>", value, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungGreaterThan(Integer value) {
			addCriterion("idnguoidung >", value, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungGreaterThanOrEqualTo(Integer value) {
			addCriterion("idnguoidung >=", value, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungLessThan(Integer value) {
			addCriterion("idnguoidung <", value, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungLessThanOrEqualTo(Integer value) {
			addCriterion("idnguoidung <=", value, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungIn(List<Integer> values) {
			addCriterion("idnguoidung in", values, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungNotIn(List<Integer> values) {
			addCriterion("idnguoidung not in", values, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungBetween(Integer value1, Integer value2) {
			addCriterion("idnguoidung between", value1, value2, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdnguoidungNotBetween(Integer value1, Integer value2) {
			addCriterion("idnguoidung not between", value1, value2, "idnguoidung");
			return (Criteria) this;
		}

		public Criteria andIdsanphamIsNull() {
			addCriterion("idsanpham is null");
			return (Criteria) this;
		}

		public Criteria andIdsanphamIsNotNull() {
			addCriterion("idsanpham is not null");
			return (Criteria) this;
		}

		public Criteria andIdsanphamEqualTo(Integer value) {
			addCriterion("idsanpham =", value, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamNotEqualTo(Integer value) {
			addCriterion("idsanpham <>", value, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamGreaterThan(Integer value) {
			addCriterion("idsanpham >", value, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamGreaterThanOrEqualTo(Integer value) {
			addCriterion("idsanpham >=", value, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamLessThan(Integer value) {
			addCriterion("idsanpham <", value, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamLessThanOrEqualTo(Integer value) {
			addCriterion("idsanpham <=", value, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamIn(List<Integer> values) {
			addCriterion("idsanpham in", values, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamNotIn(List<Integer> values) {
			addCriterion("idsanpham not in", values, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamBetween(Integer value1, Integer value2) {
			addCriterion("idsanpham between", value1, value2, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andIdsanphamNotBetween(Integer value1, Integer value2) {
			addCriterion("idsanpham not between", value1, value2, "idsanpham");
			return (Criteria) this;
		}

		public Criteria andSoluongIsNull() {
			addCriterion("soluong is null");
			return (Criteria) this;
		}

		public Criteria andSoluongIsNotNull() {
			addCriterion("soluong is not null");
			return (Criteria) this;
		}

		public Criteria andSoluongEqualTo(Integer value) {
			addCriterion("soluong =", value, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongNotEqualTo(Integer value) {
			addCriterion("soluong <>", value, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongGreaterThan(Integer value) {
			addCriterion("soluong >", value, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongGreaterThanOrEqualTo(Integer value) {
			addCriterion("soluong >=", value, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongLessThan(Integer value) {
			addCriterion("soluong <", value, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongLessThanOrEqualTo(Integer value) {
			addCriterion("soluong <=", value, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongIn(List<Integer> values) {
			addCriterion("soluong in", values, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongNotIn(List<Integer> values) {
			addCriterion("soluong not in", values, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongBetween(Integer value1, Integer value2) {
			addCriterion("soluong between", value1, value2, "soluong");
			return (Criteria) this;
		}

		public Criteria andSoluongNotBetween(Integer value1, Integer value2) {
			addCriterion("soluong not between", value1, value2, "soluong");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.cartitem
	 * @mbg.generated  Mon Feb 19 01:50:08 ICT 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.cartitem
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 19 01:00:13 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}