package com.shop.demoShop.model;

public class ghe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.id
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.ten
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.hinhanh
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private String hinhanh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.gia
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private Integer gia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.mota
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private String mota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.maGhe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private Integer maghe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Ghe.maNV
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    private Integer manv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.id
     *
     * @return the value of dbo.Ghe.id
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.id
     *
     * @param id the value for dbo.Ghe.id
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.ten
     *
     * @return the value of dbo.Ghe.ten
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.ten
     *
     * @param ten the value for dbo.Ghe.ten
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.hinhanh
     *
     * @return the value of dbo.Ghe.hinhanh
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public String getHinhanh() {
        return hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.hinhanh
     *
     * @param hinhanh the value for dbo.Ghe.hinhanh
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.gia
     *
     * @return the value of dbo.Ghe.gia
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public Integer getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.gia
     *
     * @param gia the value for dbo.Ghe.gia
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setGia(Integer gia) {
        this.gia = gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.mota
     *
     * @return the value of dbo.Ghe.mota
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public String getMota() {
        return mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.mota
     *
     * @param mota the value for dbo.Ghe.mota
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setMota(String mota) {
        this.mota = mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.maGhe
     *
     * @return the value of dbo.Ghe.maGhe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public Integer getMaghe() {
        return maghe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.maGhe
     *
     * @param maghe the value for dbo.Ghe.maGhe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setMaghe(Integer maghe) {
        this.maghe = maghe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Ghe.maNV
     *
     * @return the value of dbo.Ghe.maNV
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public Integer getManv() {
        return manv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Ghe.maNV
     *
     * @param manv the value for dbo.Ghe.maNV
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    public void setManv(Integer manv) {
        this.manv = manv;
    }
}