package com.shop.demoShop.model;

import java.util.ArrayList;
import java.util.List;

public class loaigheExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public loaigheExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdgIsNull() {
            addCriterion("idG is null");
            return (Criteria) this;
        }

        public Criteria andIdgIsNotNull() {
            addCriterion("idG is not null");
            return (Criteria) this;
        }

        public Criteria andIdgEqualTo(Integer value) {
            addCriterion("idG =", value, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgNotEqualTo(Integer value) {
            addCriterion("idG <>", value, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgGreaterThan(Integer value) {
            addCriterion("idG >", value, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgGreaterThanOrEqualTo(Integer value) {
            addCriterion("idG >=", value, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgLessThan(Integer value) {
            addCriterion("idG <", value, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgLessThanOrEqualTo(Integer value) {
            addCriterion("idG <=", value, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgIn(List<Integer> values) {
            addCriterion("idG in", values, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgNotIn(List<Integer> values) {
            addCriterion("idG not in", values, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgBetween(Integer value1, Integer value2) {
            addCriterion("idG between", value1, value2, "idg");
            return (Criteria) this;
        }

        public Criteria andIdgNotBetween(Integer value1, Integer value2) {
            addCriterion("idG not between", value1, value2, "idg");
            return (Criteria) this;
        }

        public Criteria andTengIsNull() {
            addCriterion("tenG is null");
            return (Criteria) this;
        }

        public Criteria andTengIsNotNull() {
            addCriterion("tenG is not null");
            return (Criteria) this;
        }

        public Criteria andTengEqualTo(String value) {
            addCriterion("tenG =", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengNotEqualTo(String value) {
            addCriterion("tenG <>", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengGreaterThan(String value) {
            addCriterion("tenG >", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengGreaterThanOrEqualTo(String value) {
            addCriterion("tenG >=", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengLessThan(String value) {
            addCriterion("tenG <", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengLessThanOrEqualTo(String value) {
            addCriterion("tenG <=", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengLike(String value) {
            addCriterion("tenG like", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengNotLike(String value) {
            addCriterion("tenG not like", value, "teng");
            return (Criteria) this;
        }

        public Criteria andTengIn(List<String> values) {
            addCriterion("tenG in", values, "teng");
            return (Criteria) this;
        }

        public Criteria andTengNotIn(List<String> values) {
            addCriterion("tenG not in", values, "teng");
            return (Criteria) this;
        }

        public Criteria andTengBetween(String value1, String value2) {
            addCriterion("tenG between", value1, value2, "teng");
            return (Criteria) this;
        }

        public Criteria andTengNotBetween(String value1, String value2) {
            addCriterion("tenG not between", value1, value2, "teng");
            return (Criteria) this;
        }

        public Criteria andHinhanhgIsNull() {
            addCriterion("hinhanhg is null");
            return (Criteria) this;
        }

        public Criteria andHinhanhgIsNotNull() {
            addCriterion("hinhanhg is not null");
            return (Criteria) this;
        }

        public Criteria andHinhanhgEqualTo(String value) {
            addCriterion("hinhanhg =", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgNotEqualTo(String value) {
            addCriterion("hinhanhg <>", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgGreaterThan(String value) {
            addCriterion("hinhanhg >", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgGreaterThanOrEqualTo(String value) {
            addCriterion("hinhanhg >=", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgLessThan(String value) {
            addCriterion("hinhanhg <", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgLessThanOrEqualTo(String value) {
            addCriterion("hinhanhg <=", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgLike(String value) {
            addCriterion("hinhanhg like", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgNotLike(String value) {
            addCriterion("hinhanhg not like", value, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgIn(List<String> values) {
            addCriterion("hinhanhg in", values, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgNotIn(List<String> values) {
            addCriterion("hinhanhg not in", values, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgBetween(String value1, String value2) {
            addCriterion("hinhanhg between", value1, value2, "hinhanhg");
            return (Criteria) this;
        }

        public Criteria andHinhanhgNotBetween(String value1, String value2) {
            addCriterion("hinhanhg not between", value1, value2, "hinhanhg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 31 22:24:51 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}