package com.shop.demoShop.model;

public class loaighe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.LoaiGhe.idG
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    private Integer idg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.LoaiGhe.tenG
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    private String teng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.LoaiGhe.hinhanhg
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    private String hinhanhg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.LoaiGhe.idG
     *
     * @return the value of dbo.LoaiGhe.idG
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public Integer getIdg() {
        return idg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.LoaiGhe.idG
     *
     * @param idg the value for dbo.LoaiGhe.idG
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void setIdg(Integer idg) {
        this.idg = idg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.LoaiGhe.tenG
     *
     * @return the value of dbo.LoaiGhe.tenG
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public String getTeng() {
        return teng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.LoaiGhe.tenG
     *
     * @param teng the value for dbo.LoaiGhe.tenG
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void setTeng(String teng) {
        this.teng = teng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.LoaiGhe.hinhanhg
     *
     * @return the value of dbo.LoaiGhe.hinhanhg
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public String getHinhanhg() {
        return hinhanhg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.LoaiGhe.hinhanhg
     *
     * @param hinhanhg the value for dbo.LoaiGhe.hinhanhg
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    public void setHinhanhg(String hinhanhg) {
        this.hinhanhg = hinhanhg;
    }
}