package com.WBH.dmWBH.model;


import org.springframework.validation.annotation.Validated;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
 @Validated
public class account {
    
    private Integer aid;
    
    @NotBlank(message = "Not để trống !")
    @Size(min = 5, max = 250)
    private String username;
    @NotEmpty(message = "Not để trống !")
    private String pass;
    private Integer issell;
    private Integer isadmin;
    
    @Email(message = "...@gmail.com !")
    @NotEmpty(message = "Not để trống !")
    private String email;

    public Integer getAid() {
        return aid;
    }

    public void setAid(Integer aid) {
        this.aid = aid;
    }

    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.username
     *
     * @param username the value for dbo.Account.username
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.pass
     *
     * @return the value of dbo.Account.pass
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.pass
     *
     * @param pass the value for dbo.Account.pass
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.isSell
     *
     * @return the value of dbo.Account.isSell
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public Integer getIssell() {
        return issell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.isSell
     *
     * @param issell the value for dbo.Account.isSell
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public void setIssell(Integer issell) {
        this.issell = issell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.isAdmin
     *
     * @return the value of dbo.Account.isAdmin
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.isAdmin
     *
     * @param isadmin the value for dbo.Account.isAdmin
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.Email
     *
     * @return the value of dbo.Account.Email
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.Email
     *
     * @param email the value for dbo.Account.Email
     *
     * @mbg.generated Mon Jan 15 00:54:58 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

	@Override
	public String toString() {
		return "account [aid=" + aid + ", username=" + username + ", pass=" + pass + ", issell=" + issell + ", isadmin="
				+ isadmin + ", email=" + email + "]";
	}
    
}