package com.WBH.dmWBH.model;

public class cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.idc
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    private Integer idc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.ten
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.gia
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    private Integer gia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.soluong
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    private Integer soluong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.idc
     *
     * @return the value of dbo.cart.idc
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public Integer getIdc() {
        return idc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.idc
     *
     * @param idc the value for dbo.cart.idc
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public void setIdc(Integer idc) {
        this.idc = idc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.ten
     *
     * @return the value of dbo.cart.ten
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.ten
     *
     * @param ten the value for dbo.cart.ten
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.gia
     *
     * @return the value of dbo.cart.gia
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public Integer getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.gia
     *
     * @param gia the value for dbo.cart.gia
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public void setGia(Integer gia) {
        this.gia = gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.soluong
     *
     * @return the value of dbo.cart.soluong
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public Integer getSoluong() {
        return soluong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.soluong
     *
     * @param soluong the value for dbo.cart.soluong
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
}