package com.WBH.dmWBH.model;

public class giay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Giay.cid
     *
     * @mbg.generated Sun Dec 24 01:43:03 ICT 2023
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Giay.cname
     *
     * @mbg.generated Sun Dec 24 01:43:03 ICT 2023
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Giay.cid
     *
     * @return the value of dbo.Giay.cid
     *
     * @mbg.generated Sun Dec 24 01:43:03 ICT 2023
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Giay.cid
     *
     * @param cid the value for dbo.Giay.cid
     *
     * @mbg.generated Sun Dec 24 01:43:03 ICT 2023
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Giay.cname
     *
     * @return the value of dbo.Giay.cname
     *
     * @mbg.generated Sun Dec 24 01:43:03 ICT 2023
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Giay.cname
     *
     * @param cname the value for dbo.Giay.cname
     *
     * @mbg.generated Sun Dec 24 01:43:03 ICT 2023
     */
    public void setCname(String cname) {
        this.cname = cname;
    }
}