package com.WBH.dmWBH.model;

public class sanpham {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.id
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.ten
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.hinhanh
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private String hinhanh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.gia
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private Integer gia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.mota
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private String mota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.maGiay
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private Integer magiay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.maNV
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    private Integer manv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.id
     *
     * @return the value of dbo.SanPham.id
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.id
     *
     * @param id the value for dbo.SanPham.id
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.ten
     *
     * @return the value of dbo.SanPham.ten
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.ten
     *
     * @param ten the value for dbo.SanPham.ten
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.hinhanh
     *
     * @return the value of dbo.SanPham.hinhanh
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public String getHinhanh() {
        return hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.hinhanh
     *
     * @param hinhanh the value for dbo.SanPham.hinhanh
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.gia
     *
     * @return the value of dbo.SanPham.gia
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public Integer getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.gia
     *
     * @param gia the value for dbo.SanPham.gia
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setGia(Integer gia) {
        this.gia = gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.mota
     *
     * @return the value of dbo.SanPham.mota
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public String getMota() {
        return mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.mota
     *
     * @param mota the value for dbo.SanPham.mota
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setMota(String mota) {
        this.mota = mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.maGiay
     *
     * @return the value of dbo.SanPham.maGiay
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public Integer getMagiay() {
        return magiay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.maGiay
     *
     * @param magiay the value for dbo.SanPham.maGiay
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setMagiay(Integer magiay) {
        this.magiay = magiay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.maNV
     *
     * @return the value of dbo.SanPham.maNV
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public Integer getManv() {
        return manv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.maNV
     *
     * @param manv the value for dbo.SanPham.maNV
     *
     * @mbg.generated Wed Jan 03 12:32:26 ICT 2024
     */
    public void setManv(Integer manv) {
        this.manv = manv;
    }
}