package com.NhaHang.dmNhaHang.mapper.dbo;

import com.NhaHang.dmNhaHang.model.DICHVU;
import com.NhaHang.dmNhaHang.model.DICHVUExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DICHVUMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    long countByExample(DICHVUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int deleteByExample(DICHVUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int deleteByPrimaryKey(Integer idDichvu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int insert(DICHVU row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int insertSelective(DICHVU row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    List<DICHVU> selectByExample(DICHVUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    DICHVU selectByPrimaryKey(Integer idDichvu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int updateByExampleSelective(@Param("row") DICHVU row, @Param("example") DICHVUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int updateByExample(@Param("row") DICHVU row, @Param("example") DICHVUExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int updateByPrimaryKeySelective(DICHVU row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    int updateByPrimaryKey(DICHVU row);
}