package com.webbh.dmBanhang.Model;

public class account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Account.aid
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Account.username
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Account.pass
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    private String pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Account.isSell
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    private Integer issell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Account.isAdmin
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    private Integer isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Account.Email
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.aid
     *
     * @return the value of dbo.Account.aid
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.aid
     *
     * @param aid the value for dbo.Account.aid
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.username
     *
     * @return the value of dbo.Account.username
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.username
     *
     * @param username the value for dbo.Account.username
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.pass
     *
     * @return the value of dbo.Account.pass
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.pass
     *
     * @param pass the value for dbo.Account.pass
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.isSell
     *
     * @return the value of dbo.Account.isSell
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public Integer getIssell() {
        return issell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.isSell
     *
     * @param issell the value for dbo.Account.isSell
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public void setIssell(Integer issell) {
        this.issell = issell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.isAdmin
     *
     * @return the value of dbo.Account.isAdmin
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.isAdmin
     *
     * @param isadmin the value for dbo.Account.isAdmin
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Account.Email
     *
     * @return the value of dbo.Account.Email
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Account.Email
     *
     * @param email the value for dbo.Account.Email
     *
     * @mbg.generated Thu Mar 21 00:34:52 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }
}