package com.webbh.dmBanhang.Model;

public class cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.idsp
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    private Integer idsp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.hinhanh
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    private String hinhanh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.ten
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cart.gia
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    private Integer gia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.idsp
     *
     * @return the value of dbo.cart.idsp
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public Integer getIdsp() {
        return idsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.idsp
     *
     * @param idsp the value for dbo.cart.idsp
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public void setIdsp(Integer idsp) {
        this.idsp = idsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.hinhanh
     *
     * @return the value of dbo.cart.hinhanh
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public String getHinhanh() {
        return hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.hinhanh
     *
     * @param hinhanh the value for dbo.cart.hinhanh
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.ten
     *
     * @return the value of dbo.cart.ten
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.ten
     *
     * @param ten the value for dbo.cart.ten
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cart.gia
     *
     * @return the value of dbo.cart.gia
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public Integer getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cart.gia
     *
     * @param gia the value for dbo.cart.gia
     *
     * @mbg.generated Sun Apr 07 00:25:17 ICT 2024
     */
    public void setGia(Integer gia) {
        this.gia = gia;
    }
}