package com.webbh.dmBanhang.Model;

public class hoten {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.hoten.idname
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    private Integer idname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.hoten.ten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.hoten.ho
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    private String ho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.hoten.namsinh
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    private Integer namsinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.hoten.quequan
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    private String quequan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.hoten.idname
     *
     * @return the value of dbo.hoten.idname
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public Integer getIdname() {
        return idname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.hoten.idname
     *
     * @param idname the value for dbo.hoten.idname
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setIdname(Integer idname) {
        this.idname = idname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.hoten.ten
     *
     * @return the value of dbo.hoten.ten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.hoten.ten
     *
     * @param ten the value for dbo.hoten.ten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.hoten.ho
     *
     * @return the value of dbo.hoten.ho
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public String getHo() {
        return ho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.hoten.ho
     *
     * @param ho the value for dbo.hoten.ho
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setHo(String ho) {
        this.ho = ho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.hoten.namsinh
     *
     * @return the value of dbo.hoten.namsinh
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public Integer getNamsinh() {
        return namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.hoten.namsinh
     *
     * @param namsinh the value for dbo.hoten.namsinh
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setNamsinh(Integer namsinh) {
        this.namsinh = namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.hoten.quequan
     *
     * @return the value of dbo.hoten.quequan
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public String getQuequan() {
        return quequan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.hoten.quequan
     *
     * @param quequan the value for dbo.hoten.quequan
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setQuequan(String quequan) {
        this.quequan = quequan;
    }
}