package com.webbh.dmBanhang.Model;

import java.util.ArrayList;
import java.util.List;

public class hotenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public hotenExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdnameIsNull() {
            addCriterion("idname is null");
            return (Criteria) this;
        }

        public Criteria andIdnameIsNotNull() {
            addCriterion("idname is not null");
            return (Criteria) this;
        }

        public Criteria andIdnameEqualTo(Integer value) {
            addCriterion("idname =", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotEqualTo(Integer value) {
            addCriterion("idname <>", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameGreaterThan(Integer value) {
            addCriterion("idname >", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameGreaterThanOrEqualTo(Integer value) {
            addCriterion("idname >=", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameLessThan(Integer value) {
            addCriterion("idname <", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameLessThanOrEqualTo(Integer value) {
            addCriterion("idname <=", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameIn(List<Integer> values) {
            addCriterion("idname in", values, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotIn(List<Integer> values) {
            addCriterion("idname not in", values, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameBetween(Integer value1, Integer value2) {
            addCriterion("idname between", value1, value2, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotBetween(Integer value1, Integer value2) {
            addCriterion("idname not between", value1, value2, "idname");
            return (Criteria) this;
        }

        public Criteria andTenIsNull() {
            addCriterion("ten is null");
            return (Criteria) this;
        }

        public Criteria andTenIsNotNull() {
            addCriterion("ten is not null");
            return (Criteria) this;
        }

        public Criteria andTenEqualTo(String value) {
            addCriterion("ten =", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotEqualTo(String value) {
            addCriterion("ten <>", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenGreaterThan(String value) {
            addCriterion("ten >", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenGreaterThanOrEqualTo(String value) {
            addCriterion("ten >=", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenLessThan(String value) {
            addCriterion("ten <", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenLessThanOrEqualTo(String value) {
            addCriterion("ten <=", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenLike(String value) {
            addCriterion("ten like", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotLike(String value) {
            addCriterion("ten not like", value, "ten");
            return (Criteria) this;
        }

        public Criteria andTenIn(List<String> values) {
            addCriterion("ten in", values, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotIn(List<String> values) {
            addCriterion("ten not in", values, "ten");
            return (Criteria) this;
        }

        public Criteria andTenBetween(String value1, String value2) {
            addCriterion("ten between", value1, value2, "ten");
            return (Criteria) this;
        }

        public Criteria andTenNotBetween(String value1, String value2) {
            addCriterion("ten not between", value1, value2, "ten");
            return (Criteria) this;
        }

        public Criteria andHoIsNull() {
            addCriterion("ho is null");
            return (Criteria) this;
        }

        public Criteria andHoIsNotNull() {
            addCriterion("ho is not null");
            return (Criteria) this;
        }

        public Criteria andHoEqualTo(String value) {
            addCriterion("ho =", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoNotEqualTo(String value) {
            addCriterion("ho <>", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoGreaterThan(String value) {
            addCriterion("ho >", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoGreaterThanOrEqualTo(String value) {
            addCriterion("ho >=", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoLessThan(String value) {
            addCriterion("ho <", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoLessThanOrEqualTo(String value) {
            addCriterion("ho <=", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoLike(String value) {
            addCriterion("ho like", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoNotLike(String value) {
            addCriterion("ho not like", value, "ho");
            return (Criteria) this;
        }

        public Criteria andHoIn(List<String> values) {
            addCriterion("ho in", values, "ho");
            return (Criteria) this;
        }

        public Criteria andHoNotIn(List<String> values) {
            addCriterion("ho not in", values, "ho");
            return (Criteria) this;
        }

        public Criteria andHoBetween(String value1, String value2) {
            addCriterion("ho between", value1, value2, "ho");
            return (Criteria) this;
        }

        public Criteria andHoNotBetween(String value1, String value2) {
            addCriterion("ho not between", value1, value2, "ho");
            return (Criteria) this;
        }

        public Criteria andNamsinhIsNull() {
            addCriterion("namsinh is null");
            return (Criteria) this;
        }

        public Criteria andNamsinhIsNotNull() {
            addCriterion("namsinh is not null");
            return (Criteria) this;
        }

        public Criteria andNamsinhEqualTo(Integer value) {
            addCriterion("namsinh =", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotEqualTo(Integer value) {
            addCriterion("namsinh <>", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhGreaterThan(Integer value) {
            addCriterion("namsinh >", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhGreaterThanOrEqualTo(Integer value) {
            addCriterion("namsinh >=", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhLessThan(Integer value) {
            addCriterion("namsinh <", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhLessThanOrEqualTo(Integer value) {
            addCriterion("namsinh <=", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhIn(List<Integer> values) {
            addCriterion("namsinh in", values, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotIn(List<Integer> values) {
            addCriterion("namsinh not in", values, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhBetween(Integer value1, Integer value2) {
            addCriterion("namsinh between", value1, value2, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotBetween(Integer value1, Integer value2) {
            addCriterion("namsinh not between", value1, value2, "namsinh");
            return (Criteria) this;
        }

        public Criteria andQuequanIsNull() {
            addCriterion("quequan is null");
            return (Criteria) this;
        }

        public Criteria andQuequanIsNotNull() {
            addCriterion("quequan is not null");
            return (Criteria) this;
        }

        public Criteria andQuequanEqualTo(String value) {
            addCriterion("quequan =", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanNotEqualTo(String value) {
            addCriterion("quequan <>", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanGreaterThan(String value) {
            addCriterion("quequan >", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanGreaterThanOrEqualTo(String value) {
            addCriterion("quequan >=", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanLessThan(String value) {
            addCriterion("quequan <", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanLessThanOrEqualTo(String value) {
            addCriterion("quequan <=", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanLike(String value) {
            addCriterion("quequan like", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanNotLike(String value) {
            addCriterion("quequan not like", value, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanIn(List<String> values) {
            addCriterion("quequan in", values, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanNotIn(List<String> values) {
            addCriterion("quequan not in", values, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanBetween(String value1, String value2) {
            addCriterion("quequan between", value1, value2, "quequan");
            return (Criteria) this;
        }

        public Criteria andQuequanNotBetween(String value1, String value2) {
            addCriterion("quequan not between", value1, value2, "quequan");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.hoten
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 13 22:59:09 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.hoten
     *
     * @mbg.generated Wed Mar 13 22:59:09 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}