package com.webbh.dmBanhang.Model;

public class ngaythang {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.ngaythang.thang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	private Integer thang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.ngaythang.tuan
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	private Integer tuan;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.ngaythang.thang
	 * @return  the value of dbo.ngaythang.thang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	public Integer getThang() {
		return thang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.ngaythang.thang
	 * @param thang  the value for dbo.ngaythang.thang
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	public void setThang(Integer thang) {
		this.thang = thang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.ngaythang.tuan
	 * @return  the value of dbo.ngaythang.tuan
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	public Integer getTuan() {
		return tuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.ngaythang.tuan
	 * @param tuan  the value for dbo.ngaythang.tuan
	 * @mbg.generated  Thu Apr 04 00:12:07 ICT 2024
	 */
	public void setTuan(Integer tuan) {
		this.tuan = tuan;
	}
}