package com.webbh.dmBanhang.Model;

public class sdt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.sdt.sodau
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	private Integer sodau;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.sdt.sogiua
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	private Integer sogiua;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.sdt.socuoi
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	private Integer socuoi;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.sdt.sodau
	 * @return  the value of dbo.sdt.sodau
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public Integer getSodau() {
		return sodau;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.sdt.sodau
	 * @param sodau  the value for dbo.sdt.sodau
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void setSodau(Integer sodau) {
		this.sodau = sodau;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.sdt.sogiua
	 * @return  the value of dbo.sdt.sogiua
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public Integer getSogiua() {
		return sogiua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.sdt.sogiua
	 * @param sogiua  the value for dbo.sdt.sogiua
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void setSogiua(Integer sogiua) {
		this.sogiua = sogiua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.sdt.socuoi
	 * @return  the value of dbo.sdt.socuoi
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public Integer getSocuoi() {
		return socuoi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.sdt.socuoi
	 * @param socuoi  the value for dbo.sdt.socuoi
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void setSocuoi(Integer socuoi) {
		this.socuoi = socuoi;
	}
}