package com.webbh.dmBanhang.Model;

import java.util.ArrayList;
import java.util.List;

public class sdtExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public sdtExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSodauIsNull() {
			addCriterion("sodau is null");
			return (Criteria) this;
		}

		public Criteria andSodauIsNotNull() {
			addCriterion("sodau is not null");
			return (Criteria) this;
		}

		public Criteria andSodauEqualTo(Integer value) {
			addCriterion("sodau =", value, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauNotEqualTo(Integer value) {
			addCriterion("sodau <>", value, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauGreaterThan(Integer value) {
			addCriterion("sodau >", value, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauGreaterThanOrEqualTo(Integer value) {
			addCriterion("sodau >=", value, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauLessThan(Integer value) {
			addCriterion("sodau <", value, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauLessThanOrEqualTo(Integer value) {
			addCriterion("sodau <=", value, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauIn(List<Integer> values) {
			addCriterion("sodau in", values, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauNotIn(List<Integer> values) {
			addCriterion("sodau not in", values, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauBetween(Integer value1, Integer value2) {
			addCriterion("sodau between", value1, value2, "sodau");
			return (Criteria) this;
		}

		public Criteria andSodauNotBetween(Integer value1, Integer value2) {
			addCriterion("sodau not between", value1, value2, "sodau");
			return (Criteria) this;
		}

		public Criteria andSogiuaIsNull() {
			addCriterion("sogiua is null");
			return (Criteria) this;
		}

		public Criteria andSogiuaIsNotNull() {
			addCriterion("sogiua is not null");
			return (Criteria) this;
		}

		public Criteria andSogiuaEqualTo(Integer value) {
			addCriterion("sogiua =", value, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaNotEqualTo(Integer value) {
			addCriterion("sogiua <>", value, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaGreaterThan(Integer value) {
			addCriterion("sogiua >", value, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaGreaterThanOrEqualTo(Integer value) {
			addCriterion("sogiua >=", value, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaLessThan(Integer value) {
			addCriterion("sogiua <", value, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaLessThanOrEqualTo(Integer value) {
			addCriterion("sogiua <=", value, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaIn(List<Integer> values) {
			addCriterion("sogiua in", values, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaNotIn(List<Integer> values) {
			addCriterion("sogiua not in", values, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaBetween(Integer value1, Integer value2) {
			addCriterion("sogiua between", value1, value2, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSogiuaNotBetween(Integer value1, Integer value2) {
			addCriterion("sogiua not between", value1, value2, "sogiua");
			return (Criteria) this;
		}

		public Criteria andSocuoiIsNull() {
			addCriterion("socuoi is null");
			return (Criteria) this;
		}

		public Criteria andSocuoiIsNotNull() {
			addCriterion("socuoi is not null");
			return (Criteria) this;
		}

		public Criteria andSocuoiEqualTo(Integer value) {
			addCriterion("socuoi =", value, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiNotEqualTo(Integer value) {
			addCriterion("socuoi <>", value, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiGreaterThan(Integer value) {
			addCriterion("socuoi >", value, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiGreaterThanOrEqualTo(Integer value) {
			addCriterion("socuoi >=", value, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiLessThan(Integer value) {
			addCriterion("socuoi <", value, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiLessThanOrEqualTo(Integer value) {
			addCriterion("socuoi <=", value, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiIn(List<Integer> values) {
			addCriterion("socuoi in", values, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiNotIn(List<Integer> values) {
			addCriterion("socuoi not in", values, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiBetween(Integer value1, Integer value2) {
			addCriterion("socuoi between", value1, value2, "socuoi");
			return (Criteria) this;
		}

		public Criteria andSocuoiNotBetween(Integer value1, Integer value2) {
			addCriterion("socuoi not between", value1, value2, "socuoi");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.sdt
	 * @mbg.generated  Tue Apr 02 21:11:14 ICT 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.sdt
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 02 20:52:07 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}