package com.example.demo.model;

public class sanpham {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.tensanpham
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    private String tensanpham;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.gia
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    private String gia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.SanPham.mota
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    private String mota;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.tensanpham
     *
     * @return the value of dbo.SanPham.tensanpham
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    public String getTensanpham() {
        return tensanpham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.tensanpham
     *
     * @param tensanpham the value for dbo.SanPham.tensanpham
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    public void setTensanpham(String tensanpham) {
        this.tensanpham = tensanpham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.gia
     *
     * @return the value of dbo.SanPham.gia
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    public String getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.gia
     *
     * @param gia the value for dbo.SanPham.gia
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    public void setGia(String gia) {
        this.gia = gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.SanPham.mota
     *
     * @return the value of dbo.SanPham.mota
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    public String getMota() {
        return mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.SanPham.mota
     *
     * @param mota the value for dbo.SanPham.mota
     *
     * @mbg.generated Sun Nov 26 16:31:39 ICT 2023
     */
    public void setMota(String mota) {
        this.mota = mota;
    }
}