package com.example.demo.mapper.dbo;

import com.example.demo.model.dangnhap;
import com.example.demo.model.dangnhapExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface dangnhapMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	long countByExample(dangnhapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	int deleteByExample(dangnhapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	int insert(dangnhap row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	int insertSelective(dangnhap row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	List<dangnhap> selectByExample(dangnhapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") dangnhap row, @Param("example") dangnhapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dbo.DANGNHAP
	 *
	 * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
	 */
	int updateByExample(@Param("row") dangnhap row, @Param("example") dangnhapExample example);

	dangnhap checklogin(@Param("username") String username, @Param("password") String password);
	int doipass(@Param("newpassword") String newpassword,@Param("password") String password );
	int signup(@Param("username") String username, @Param("password") String password);
}