package com.example.demo.mapper.dbo;

import com.example.demo.model.sanpham;
import com.example.demo.model.sanphamExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface sanphamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    long countByExample(sanphamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    int deleteByExample(sanphamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    int insert(sanpham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    int insertSelective(sanpham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    List<sanpham> selectByExample(sanphamExample example);
    sanpham findById(@Param("id") int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    int updateByExampleSelective(@Param("row") sanpham row, @Param("example") sanphamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    int updateByExample(@Param("row") sanpham row, @Param("example") sanphamExample example);
    int addSP (@Param("tensanpham")String tensanpham , @Param("gia")String gia ,@Param("mota")String mota );
    int deleteTenSp (@Param("id") int id);
    int upgia(@Param("tensanpham") String tensanpham,@Param("gia") String gia,@Param("mota") String mota,@Param("id") int id );
}