	package com.example.demo.mapper.dbo;

import com.example.demo.model.hanghoa;
import com.example.demo.model.hanghoaExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface hanghoaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    long countByExample(hanghoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    int deleteByExample(hanghoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    int insert(@Param("a") String a, @Param("b") int b);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    int insertSelective(hanghoa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    List<hanghoa> selectByExample(hanghoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    int updateByExampleSelective(@Param("row") hanghoa row, @Param("example") hanghoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HANGHOA
     *
     * @mbg.generated Wed Nov 15 14:50:52 ICT 2023
     */
    int updateByExample(@Param("a") String a, @Param("b") String b);
}