package com.example.demo.model;

public class dangnhap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.DANGNHAP.username
     *
     * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.DANGNHAP.passwork
     *
     * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
     */
    private String passwork;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.DANGNHAP.username
     *
     * @return the value of dbo.DANGNHAP.username
     *
     * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.DANGNHAP.username
     *
     * @param username the value for dbo.DANGNHAP.username
     *
     * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.DANGNHAP.passwork
     *
     * @return the value of dbo.DANGNHAP.passwork
     *
     * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
     */
    public String getPasswork() {
        return passwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.DANGNHAP.passwork
     *
     * @param passwork the value for dbo.DANGNHAP.passwork
     *
     * @mbg.generated Thu Nov 23 21:31:13 ICT 2023
     */
    public void setPasswork(String passwork) {
        this.passwork = passwork;
    }
}