package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class sanphamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public sanphamExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTensanphamIsNull() {
            addCriterion("tensanpham is null");
            return (Criteria) this;
        }

        public Criteria andTensanphamIsNotNull() {
            addCriterion("tensanpham is not null");
            return (Criteria) this;
        }

        public Criteria andTensanphamEqualTo(String value) {
            addCriterion("tensanpham =", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamNotEqualTo(String value) {
            addCriterion("tensanpham <>", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamGreaterThan(String value) {
            addCriterion("tensanpham >", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamGreaterThanOrEqualTo(String value) {
            addCriterion("tensanpham >=", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamLessThan(String value) {
            addCriterion("tensanpham <", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamLessThanOrEqualTo(String value) {
            addCriterion("tensanpham <=", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamLike(String value) {
            addCriterion("tensanpham like", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamNotLike(String value) {
            addCriterion("tensanpham not like", value, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamIn(List<String> values) {
            addCriterion("tensanpham in", values, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamNotIn(List<String> values) {
            addCriterion("tensanpham not in", values, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamBetween(String value1, String value2) {
            addCriterion("tensanpham between", value1, value2, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andTensanphamNotBetween(String value1, String value2) {
            addCriterion("tensanpham not between", value1, value2, "tensanpham");
            return (Criteria) this;
        }

        public Criteria andGiaIsNull() {
            addCriterion("gia is null");
            return (Criteria) this;
        }

        public Criteria andGiaIsNotNull() {
            addCriterion("gia is not null");
            return (Criteria) this;
        }

        public Criteria andGiaEqualTo(String value) {
            addCriterion("gia =", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotEqualTo(String value) {
            addCriterion("gia <>", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaGreaterThan(String value) {
            addCriterion("gia >", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaGreaterThanOrEqualTo(String value) {
            addCriterion("gia >=", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaLessThan(String value) {
            addCriterion("gia <", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaLessThanOrEqualTo(String value) {
            addCriterion("gia <=", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaLike(String value) {
            addCriterion("gia like", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotLike(String value) {
            addCriterion("gia not like", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaIn(List<String> values) {
            addCriterion("gia in", values, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotIn(List<String> values) {
            addCriterion("gia not in", values, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaBetween(String value1, String value2) {
            addCriterion("gia between", value1, value2, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotBetween(String value1, String value2) {
            addCriterion("gia not between", value1, value2, "gia");
            return (Criteria) this;
        }

        public Criteria andMotaIsNull() {
            addCriterion("mota is null");
            return (Criteria) this;
        }

        public Criteria andMotaIsNotNull() {
            addCriterion("mota is not null");
            return (Criteria) this;
        }

        public Criteria andMotaEqualTo(String value) {
            addCriterion("mota =", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotEqualTo(String value) {
            addCriterion("mota <>", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaGreaterThan(String value) {
            addCriterion("mota >", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaGreaterThanOrEqualTo(String value) {
            addCriterion("mota >=", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaLessThan(String value) {
            addCriterion("mota <", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaLessThanOrEqualTo(String value) {
            addCriterion("mota <=", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaLike(String value) {
            addCriterion("mota like", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotLike(String value) {
            addCriterion("mota not like", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaIn(List<String> values) {
            addCriterion("mota in", values, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotIn(List<String> values) {
            addCriterion("mota not in", values, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaBetween(String value1, String value2) {
            addCriterion("mota between", value1, value2, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotBetween(String value1, String value2) {
            addCriterion("mota not between", value1, value2, "mota");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.SanPham
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 13 13:27:34 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.SanPham
     *
     * @mbg.generated Wed Dec 13 13:27:34 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}