package com.NhaHang.dmNhaHang.model;

public class DICHVU {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.DICHVU.id_dichvu
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    private Integer idDichvu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.DICHVU.tendichvu
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    private String tendichvu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.DICHVU.gia
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    private String gia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.DICHVU.id_dichvu
     *
     * @return the value of dbo.DICHVU.id_dichvu
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public Integer getIdDichvu() {
        return idDichvu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.DICHVU.id_dichvu
     *
     * @param idDichvu the value for dbo.DICHVU.id_dichvu
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void setIdDichvu(Integer idDichvu) {
        this.idDichvu = idDichvu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.DICHVU.tendichvu
     *
     * @return the value of dbo.DICHVU.tendichvu
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public String getTendichvu() {
        return tendichvu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.DICHVU.tendichvu
     *
     * @param tendichvu the value for dbo.DICHVU.tendichvu
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void setTendichvu(String tendichvu) {
        this.tendichvu = tendichvu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.DICHVU.gia
     *
     * @return the value of dbo.DICHVU.gia
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public String getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.DICHVU.gia
     *
     * @param gia the value for dbo.DICHVU.gia
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void setGia(String gia) {
        this.gia = gia;
    }
}