package com.NhaHang.dmNhaHang.model;

import java.util.ArrayList;
import java.util.List;

public class DICHVUExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public DICHVUExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdDichvuIsNull() {
            addCriterion("id_dichvu is null");
            return (Criteria) this;
        }

        public Criteria andIdDichvuIsNotNull() {
            addCriterion("id_dichvu is not null");
            return (Criteria) this;
        }

        public Criteria andIdDichvuEqualTo(Integer value) {
            addCriterion("id_dichvu =", value, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuNotEqualTo(Integer value) {
            addCriterion("id_dichvu <>", value, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuGreaterThan(Integer value) {
            addCriterion("id_dichvu >", value, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_dichvu >=", value, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuLessThan(Integer value) {
            addCriterion("id_dichvu <", value, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuLessThanOrEqualTo(Integer value) {
            addCriterion("id_dichvu <=", value, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuIn(List<Integer> values) {
            addCriterion("id_dichvu in", values, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuNotIn(List<Integer> values) {
            addCriterion("id_dichvu not in", values, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuBetween(Integer value1, Integer value2) {
            addCriterion("id_dichvu between", value1, value2, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andIdDichvuNotBetween(Integer value1, Integer value2) {
            addCriterion("id_dichvu not between", value1, value2, "idDichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuIsNull() {
            addCriterion("tendichvu is null");
            return (Criteria) this;
        }

        public Criteria andTendichvuIsNotNull() {
            addCriterion("tendichvu is not null");
            return (Criteria) this;
        }

        public Criteria andTendichvuEqualTo(String value) {
            addCriterion("tendichvu =", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuNotEqualTo(String value) {
            addCriterion("tendichvu <>", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuGreaterThan(String value) {
            addCriterion("tendichvu >", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuGreaterThanOrEqualTo(String value) {
            addCriterion("tendichvu >=", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuLessThan(String value) {
            addCriterion("tendichvu <", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuLessThanOrEqualTo(String value) {
            addCriterion("tendichvu <=", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuLike(String value) {
            addCriterion("tendichvu like", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuNotLike(String value) {
            addCriterion("tendichvu not like", value, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuIn(List<String> values) {
            addCriterion("tendichvu in", values, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuNotIn(List<String> values) {
            addCriterion("tendichvu not in", values, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuBetween(String value1, String value2) {
            addCriterion("tendichvu between", value1, value2, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andTendichvuNotBetween(String value1, String value2) {
            addCriterion("tendichvu not between", value1, value2, "tendichvu");
            return (Criteria) this;
        }

        public Criteria andGiaIsNull() {
            addCriterion("gia is null");
            return (Criteria) this;
        }

        public Criteria andGiaIsNotNull() {
            addCriterion("gia is not null");
            return (Criteria) this;
        }

        public Criteria andGiaEqualTo(String value) {
            addCriterion("gia =", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotEqualTo(String value) {
            addCriterion("gia <>", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaGreaterThan(String value) {
            addCriterion("gia >", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaGreaterThanOrEqualTo(String value) {
            addCriterion("gia >=", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaLessThan(String value) {
            addCriterion("gia <", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaLessThanOrEqualTo(String value) {
            addCriterion("gia <=", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaLike(String value) {
            addCriterion("gia like", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotLike(String value) {
            addCriterion("gia not like", value, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaIn(List<String> values) {
            addCriterion("gia in", values, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotIn(List<String> values) {
            addCriterion("gia not in", values, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaBetween(String value1, String value2) {
            addCriterion("gia between", value1, value2, "gia");
            return (Criteria) this;
        }

        public Criteria andGiaNotBetween(String value1, String value2) {
            addCriterion("gia not between", value1, value2, "gia");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 18 19:27:26 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.DICHVU
     *
     * @mbg.generated Mon Dec 18 19:27:26 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}