package com.NhaHang.dmNhaHang.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class THONGTINTHIEPCUOIExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public THONGTINTHIEPCUOIExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTencodauIsNull() {
            addCriterion("tencodau is null");
            return (Criteria) this;
        }

        public Criteria andTencodauIsNotNull() {
            addCriterion("tencodau is not null");
            return (Criteria) this;
        }

        public Criteria andTencodauEqualTo(String value) {
            addCriterion("tencodau =", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauNotEqualTo(String value) {
            addCriterion("tencodau <>", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauGreaterThan(String value) {
            addCriterion("tencodau >", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauGreaterThanOrEqualTo(String value) {
            addCriterion("tencodau >=", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauLessThan(String value) {
            addCriterion("tencodau <", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauLessThanOrEqualTo(String value) {
            addCriterion("tencodau <=", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauLike(String value) {
            addCriterion("tencodau like", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauNotLike(String value) {
            addCriterion("tencodau not like", value, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauIn(List<String> values) {
            addCriterion("tencodau in", values, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauNotIn(List<String> values) {
            addCriterion("tencodau not in", values, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauBetween(String value1, String value2) {
            addCriterion("tencodau between", value1, value2, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTencodauNotBetween(String value1, String value2) {
            addCriterion("tencodau not between", value1, value2, "tencodau");
            return (Criteria) this;
        }

        public Criteria andTenchureIsNull() {
            addCriterion("tenchure is null");
            return (Criteria) this;
        }

        public Criteria andTenchureIsNotNull() {
            addCriterion("tenchure is not null");
            return (Criteria) this;
        }

        public Criteria andTenchureEqualTo(String value) {
            addCriterion("tenchure =", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureNotEqualTo(String value) {
            addCriterion("tenchure <>", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureGreaterThan(String value) {
            addCriterion("tenchure >", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureGreaterThanOrEqualTo(String value) {
            addCriterion("tenchure >=", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureLessThan(String value) {
            addCriterion("tenchure <", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureLessThanOrEqualTo(String value) {
            addCriterion("tenchure <=", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureLike(String value) {
            addCriterion("tenchure like", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureNotLike(String value) {
            addCriterion("tenchure not like", value, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureIn(List<String> values) {
            addCriterion("tenchure in", values, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureNotIn(List<String> values) {
            addCriterion("tenchure not in", values, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureBetween(String value1, String value2) {
            addCriterion("tenchure between", value1, value2, "tenchure");
            return (Criteria) this;
        }

        public Criteria andTenchureNotBetween(String value1, String value2) {
            addCriterion("tenchure not between", value1, value2, "tenchure");
            return (Criteria) this;
        }

        public Criteria andSoluongbanIsNull() {
            addCriterion("SoLuongBan is null");
            return (Criteria) this;
        }

        public Criteria andSoluongbanIsNotNull() {
            addCriterion("SoLuongBan is not null");
            return (Criteria) this;
        }

        public Criteria andSoluongbanEqualTo(Integer value) {
            addCriterion("SoLuongBan =", value, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanNotEqualTo(Integer value) {
            addCriterion("SoLuongBan <>", value, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanGreaterThan(Integer value) {
            addCriterion("SoLuongBan >", value, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanGreaterThanOrEqualTo(Integer value) {
            addCriterion("SoLuongBan >=", value, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanLessThan(Integer value) {
            addCriterion("SoLuongBan <", value, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanLessThanOrEqualTo(Integer value) {
            addCriterion("SoLuongBan <=", value, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanIn(List<Integer> values) {
            addCriterion("SoLuongBan in", values, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanNotIn(List<Integer> values) {
            addCriterion("SoLuongBan not in", values, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanBetween(Integer value1, Integer value2) {
            addCriterion("SoLuongBan between", value1, value2, "soluongban");
            return (Criteria) this;
        }

        public Criteria andSoluongbanNotBetween(Integer value1, Integer value2) {
            addCriterion("SoLuongBan not between", value1, value2, "soluongban");
            return (Criteria) this;
        }

        public Criteria andDongiaIsNull() {
            addCriterion("DonGia is null");
            return (Criteria) this;
        }

        public Criteria andDongiaIsNotNull() {
            addCriterion("DonGia is not null");
            return (Criteria) this;
        }

        public Criteria andDongiaEqualTo(Integer value) {
            addCriterion("DonGia =", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaNotEqualTo(Integer value) {
            addCriterion("DonGia <>", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaGreaterThan(Integer value) {
            addCriterion("DonGia >", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaGreaterThanOrEqualTo(Integer value) {
            addCriterion("DonGia >=", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaLessThan(Integer value) {
            addCriterion("DonGia <", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaLessThanOrEqualTo(Integer value) {
            addCriterion("DonGia <=", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaIn(List<Integer> values) {
            addCriterion("DonGia in", values, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaNotIn(List<Integer> values) {
            addCriterion("DonGia not in", values, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaBetween(Integer value1, Integer value2) {
            addCriterion("DonGia between", value1, value2, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaNotBetween(Integer value1, Integer value2) {
            addCriterion("DonGia not between", value1, value2, "dongia");
            return (Criteria) this;
        }

        public Criteria andDichvudikemIsNull() {
            addCriterion("DichVuDiKem is null");
            return (Criteria) this;
        }

        public Criteria andDichvudikemIsNotNull() {
            addCriterion("DichVuDiKem is not null");
            return (Criteria) this;
        }

        public Criteria andDichvudikemEqualTo(Integer value) {
            addCriterion("DichVuDiKem =", value, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemNotEqualTo(Integer value) {
            addCriterion("DichVuDiKem <>", value, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemGreaterThan(Integer value) {
            addCriterion("DichVuDiKem >", value, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemGreaterThanOrEqualTo(Integer value) {
            addCriterion("DichVuDiKem >=", value, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemLessThan(Integer value) {
            addCriterion("DichVuDiKem <", value, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemLessThanOrEqualTo(Integer value) {
            addCriterion("DichVuDiKem <=", value, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemIn(List<Integer> values) {
            addCriterion("DichVuDiKem in", values, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemNotIn(List<Integer> values) {
            addCriterion("DichVuDiKem not in", values, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemBetween(Integer value1, Integer value2) {
            addCriterion("DichVuDiKem between", value1, value2, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andDichvudikemNotBetween(Integer value1, Integer value2) {
            addCriterion("DichVuDiKem not between", value1, value2, "dichvudikem");
            return (Criteria) this;
        }

        public Criteria andTiendatcocIsNull() {
            addCriterion("TienDatCoc is null");
            return (Criteria) this;
        }

        public Criteria andTiendatcocIsNotNull() {
            addCriterion("TienDatCoc is not null");
            return (Criteria) this;
        }

        public Criteria andTiendatcocEqualTo(Integer value) {
            addCriterion("TienDatCoc =", value, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocNotEqualTo(Integer value) {
            addCriterion("TienDatCoc <>", value, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocGreaterThan(Integer value) {
            addCriterion("TienDatCoc >", value, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocGreaterThanOrEqualTo(Integer value) {
            addCriterion("TienDatCoc >=", value, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocLessThan(Integer value) {
            addCriterion("TienDatCoc <", value, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocLessThanOrEqualTo(Integer value) {
            addCriterion("TienDatCoc <=", value, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocIn(List<Integer> values) {
            addCriterion("TienDatCoc in", values, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocNotIn(List<Integer> values) {
            addCriterion("TienDatCoc not in", values, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocBetween(Integer value1, Integer value2) {
            addCriterion("TienDatCoc between", value1, value2, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTiendatcocNotBetween(Integer value1, Integer value2) {
            addCriterion("TienDatCoc not between", value1, value2, "tiendatcoc");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanIsNull() {
            addCriterion("TienThanhToan is null");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanIsNotNull() {
            addCriterion("TienThanhToan is not null");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanEqualTo(Integer value) {
            addCriterion("TienThanhToan =", value, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanNotEqualTo(Integer value) {
            addCriterion("TienThanhToan <>", value, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanGreaterThan(Integer value) {
            addCriterion("TienThanhToan >", value, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanGreaterThanOrEqualTo(Integer value) {
            addCriterion("TienThanhToan >=", value, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanLessThan(Integer value) {
            addCriterion("TienThanhToan <", value, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanLessThanOrEqualTo(Integer value) {
            addCriterion("TienThanhToan <=", value, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanIn(List<Integer> values) {
            addCriterion("TienThanhToan in", values, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanNotIn(List<Integer> values) {
            addCriterion("TienThanhToan not in", values, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanBetween(Integer value1, Integer value2) {
            addCriterion("TienThanhToan between", value1, value2, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andTienthanhtoanNotBetween(Integer value1, Integer value2) {
            addCriterion("TienThanhToan not between", value1, value2, "tienthanhtoan");
            return (Criteria) this;
        }

        public Criteria andGhichuIsNull() {
            addCriterion("GhiChu is null");
            return (Criteria) this;
        }

        public Criteria andGhichuIsNotNull() {
            addCriterion("GhiChu is not null");
            return (Criteria) this;
        }

        public Criteria andGhichuEqualTo(String value) {
            addCriterion("GhiChu =", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuNotEqualTo(String value) {
            addCriterion("GhiChu <>", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuGreaterThan(String value) {
            addCriterion("GhiChu >", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuGreaterThanOrEqualTo(String value) {
            addCriterion("GhiChu >=", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuLessThan(String value) {
            addCriterion("GhiChu <", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuLessThanOrEqualTo(String value) {
            addCriterion("GhiChu <=", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuLike(String value) {
            addCriterion("GhiChu like", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuNotLike(String value) {
            addCriterion("GhiChu not like", value, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuIn(List<String> values) {
            addCriterion("GhiChu in", values, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuNotIn(List<String> values) {
            addCriterion("GhiChu not in", values, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuBetween(String value1, String value2) {
            addCriterion("GhiChu between", value1, value2, "ghichu");
            return (Criteria) this;
        }

        public Criteria andGhichuNotBetween(String value1, String value2) {
            addCriterion("GhiChu not between", value1, value2, "ghichu");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiIsNull() {
            addCriterion("THONGTINTHIEPCUOI is null");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiIsNotNull() {
            addCriterion("THONGTINTHIEPCUOI is not null");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiEqualTo(Date value) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI =", value, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiNotEqualTo(Date value) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI <>", value, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiGreaterThan(Date value) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI >", value, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI >=", value, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiLessThan(Date value) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI <", value, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI <=", value, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiIn(List<Date> values) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI in", values, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiNotIn(List<Date> values) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI not in", values, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI between", value1, value2, "thongtinthiepcuoi");
            return (Criteria) this;
        }

        public Criteria andThongtinthiepcuoiNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("THONGTINTHIEPCUOI not between", value1, value2, "thongtinthiepcuoi");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 18 01:33:58 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}