package com.NhaHang.dmNhaHang.model;

import java.util.Date;

public class THONGTINTHIEPCUOI {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.id
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.tencodau
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private String tencodau;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.tenchure
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private String tenchure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.SoLuongBan
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Integer soluongban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.DonGia
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Integer dongia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.DichVuDiKem
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Integer dichvudikem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.TienDatCoc
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Integer tiendatcoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.TienThanhToan
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Integer tienthanhtoan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.GhiChu
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private String ghichu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.THONGTINTHIEPCUOI.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    private Date thongtinthiepcuoi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.id
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.id
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.id
     *
     * @param id the value for dbo.THONGTINTHIEPCUOI.id
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.tencodau
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.tencodau
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public String getTencodau() {
        return tencodau;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.tencodau
     *
     * @param tencodau the value for dbo.THONGTINTHIEPCUOI.tencodau
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setTencodau(String tencodau) {
        this.tencodau = tencodau;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.tenchure
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.tenchure
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public String getTenchure() {
        return tenchure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.tenchure
     *
     * @param tenchure the value for dbo.THONGTINTHIEPCUOI.tenchure
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setTenchure(String tenchure) {
        this.tenchure = tenchure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.SoLuongBan
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.SoLuongBan
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Integer getSoluongban() {
        return soluongban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.SoLuongBan
     *
     * @param soluongban the value for dbo.THONGTINTHIEPCUOI.SoLuongBan
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setSoluongban(Integer soluongban) {
        this.soluongban = soluongban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.DonGia
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.DonGia
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Integer getDongia() {
        return dongia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.DonGia
     *
     * @param dongia the value for dbo.THONGTINTHIEPCUOI.DonGia
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setDongia(Integer dongia) {
        this.dongia = dongia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.DichVuDiKem
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.DichVuDiKem
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Integer getDichvudikem() {
        return dichvudikem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.DichVuDiKem
     *
     * @param dichvudikem the value for dbo.THONGTINTHIEPCUOI.DichVuDiKem
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setDichvudikem(Integer dichvudikem) {
        this.dichvudikem = dichvudikem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.TienDatCoc
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.TienDatCoc
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Integer getTiendatcoc() {
        return tiendatcoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.TienDatCoc
     *
     * @param tiendatcoc the value for dbo.THONGTINTHIEPCUOI.TienDatCoc
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setTiendatcoc(Integer tiendatcoc) {
        this.tiendatcoc = tiendatcoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.TienThanhToan
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.TienThanhToan
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Integer getTienthanhtoan() {
        return tienthanhtoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.TienThanhToan
     *
     * @param tienthanhtoan the value for dbo.THONGTINTHIEPCUOI.TienThanhToan
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setTienthanhtoan(Integer tienthanhtoan) {
        this.tienthanhtoan = tienthanhtoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.GhiChu
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.GhiChu
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public String getGhichu() {
        return ghichu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.GhiChu
     *
     * @param ghichu the value for dbo.THONGTINTHIEPCUOI.GhiChu
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.THONGTINTHIEPCUOI.THONGTINTHIEPCUOI
     *
     * @return the value of dbo.THONGTINTHIEPCUOI.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public Date getThongtinthiepcuoi() {
        return thongtinthiepcuoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.THONGTINTHIEPCUOI.THONGTINTHIEPCUOI
     *
     * @param thongtinthiepcuoi the value for dbo.THONGTINTHIEPCUOI.THONGTINTHIEPCUOI
     *
     * @mbg.generated Mon Dec 18 01:33:58 ICT 2023
     */
    public void setThongtinthiepcuoi(Date thongtinthiepcuoi) {
        this.thongtinthiepcuoi = thongtinthiepcuoi;
    }
}