package com.shop.demoShop.mapper.dbo;

import com.shop.demoShop.model.ghe;
import com.shop.demoShop.model.gheExample;
import com.shop.demoShop.model.loaighe;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
@Mapper
public interface gheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    long countByExample(gheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int deleteByExample(gheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int insert(ghe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int insertSelective(ghe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    List<ghe> selectByExample(gheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    ghe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int updateByExampleSelective(@Param("row") ghe row, @Param("example") gheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int updateByExample(@Param("row") ghe row, @Param("example") gheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int updateByPrimaryKeySelective(ghe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Ghe
     *
     * @mbg.generated Thu Feb 01 15:23:34 ICT 2024
     */
    int updateByPrimaryKey(ghe row);
    List<ghe> phanloaighe(@Param("idg") int idg);
    List<ghe> phantrangtheomaghe(@Param("idg") int idg , @Param("offset") int offset ,@Param("pagesize") int pagesize );
    List<ghe> getAll();
    List<ghe> getSPbySize(@Param("offset") int offset ,@Param("pagesize") int pagesize);
    List<ghe> phantrangtheoSearch(@Param("ten") String ten,@Param("offset") int offset ,@Param("pagesize") int pagesize);
    List<ghe> search(@Param("ten") String ten);
    ghe detel (@Param("id") int id);
    List<ghe> getByMaNv(@Param("manv") int manv);
    int insertSP (@Param("ten") String ten , @Param("hinhanh") String hinhanh , @Param("gia") int gia, @Param("mota") String mota,
    				@Param("maghe") int maghe , @Param("manv") int manv);
    int deletebyID(@Param("id") int id);
    int updatebyID(@Param("ten") String ten , @Param("hinhanh") String hinhanh , @Param("gia") int gia, @Param("mota") String mota,
			@Param("maghe") int maghe, @Param("id") int id);
    ghe findById(@Param("id") int id);


}