package com.shop.demoShop.mapper.dbo;

import com.shop.demoShop.model.loaighe;
import com.shop.demoShop.model.loaigheExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface loaigheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    long countByExample(loaigheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int deleteByExample(loaigheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int deleteByPrimaryKey(Integer idg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int insert(loaighe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int insertSelective(loaighe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    List<loaighe> selectByExample(loaigheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    loaighe selectByPrimaryKey(Integer idg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int updateByExampleSelective(@Param("row") loaighe row, @Param("example") loaigheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int updateByExample(@Param("row") loaighe row, @Param("example") loaigheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int updateByPrimaryKeySelective(loaighe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.LoaiGhe
     *
     * @mbg.generated Wed Jan 31 22:24:51 ICT 2024
     */
    int updateByPrimaryKey(loaighe row);
    List<loaighe> phanloaighe(@Param("idg") int idg);

}