package com.WBH.dmWBH.mapper.dbo;

import com.WBH.dmWBH.model.cart;
import com.WBH.dmWBH.model.cartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface cartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    long countByExample(cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int deleteByExample(cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int deleteByPrimaryKey(Integer idc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int insert(cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int insertSelective(cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    List<cart> selectByExample(cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    cart selectByPrimaryKey(Integer idc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int updateByExampleSelective(@Param("row") cart row, @Param("example") cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int updateByExample(@Param("row") cart row, @Param("example") cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int updateByPrimaryKeySelective(cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cart
     *
     * @mbg.generated Wed Jan 24 18:52:47 ICT 2024
     */
    int updateByPrimaryKey(cart row);
}